### ISSUE TITLE
Frontend: Missing JSON files

### ISSUE THREAD

**Issue by devanshamin** [alexbui91/INGREX#1]
Thank you for open-sourcing INGREX. I'm trying to run the front-end server where I ran into some errors due to missing JSON files.

Below is the screenshot of the error,
<img width="848" alt="image" src="https://user-images.githubusercontent.com/56516274/209845177-087746d3-cefc-4031-b54c-5493929751e5.png">

Could you please add the below JSON files to the [sc_viz/src/app/pagerank/data](https://github.com/alexbui91/INGREX/tree/main/sc_viz/src/app/pagerank/data) directory,
* cora.json
* cora_nrank2.json
* tree_grid_kmd.json
* tree_grid.json

OR

In the [sc_viz/src/app/pagerank/data/.gitignore](https://github.com/alexbui91/INGREX/blob/main/sc_viz/src/app/pagerank/data/.gitignore), you have ignored the JSON files. Could you please explain how to generate these JSON files?.

**Comment by alexbui91** [comment]
Thank you for being interested in my code. I will make a commit including these files if they are smaller than 25MB.

**Comment by alexbui91** [comment]
The JSON file is extracted from an explainable GNN model implemented in DGL.

**Comment by devanshamin** [comment]
Thank you for providing the JSON files. I'm able to run the application.
