### ISSUE TITLE
Node Prediction Explanation not working

### ISSUE THREAD

**Issue by devanshamin** [alexbui91/INGREX#2]
I'm able to run the NodeJS server and using the application. However, I can only use the `Global Visualization` tab. The `Node Prediction Example` returns a blank screen,
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/56516274/210439052-884a1b29-d819-4651-899c-f623f8ed5578.png">

I have the flask server also running but there seems to be no requests being made to the flask server by the front end application.  Could you please point out where in the front end application the request is being made to the flask application and how does the front end application know what URL the flask app is running on?.

Sidenote:
For the `Feature Attribution` tab, [you have hardcoded your IP address](https://github.com/alexbui91/INGREX/blob/dff70788b16e5ff46762f35a03b258bcaa83d0fb/sc_viz/src/app/feature/feature.component.ts#L11). Hence, it will not work for others. Could you change that and add the URL to some config file where the user can add their own IP address and modify the URL. I'm proficient in Python but not TypeScript.

Thank you.

**Comment by alexbui91** [comment]
Yes, it is. If you run both python server and angular server on the same machine, simply changing the IP address to 0.0.0.0 or 127.0.0.1 should work.
